name: Call Birthday Cron API every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (UTC)
  workflow_dispatch:       # Allows manual run from GitHub UI

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel Birthday Cron API
        run: |
          curl -X GET "https://birthday-wishify-7y73.vercel.app/api/birthday-cron/schedule"
